Repository coffee-meet/frontend, pull requests merged in 2023-10, with the labels that each got.

#14 refactor: build-test.yml 파일 수정
  .github/workflows/build-test.yml
Labels: 🧹 Refactor

#15 feature: deploy.yml 파일 추가
  .github/workflows/deploy.yml
  .husky/pre-push
Labels: ⚙️ Feature

#19 [Style] 모바일 레이아웃 작업
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  public/coffee.png
  public/favicon.svg
  public/manifest.json
  src/App.tsx
  src/components/layouts/Layout.tsx
Labels: 🎨 Design

#23 deploy: 초기 배포
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .husky/pre-push
  index.html
  package-lock.json
  package.json
  public/coffee.png
  public/favicon.svg
  public/manifest.json
  src/App.tsx
  src/components/layouts/Layout.tsx
  src/main.tsx
  src/styles/emotion.d.ts
  src/styles/global.ts
  src/styles/index.ts
  src/styles/index.tsx
  src/styles/palette.ts
  src/styles/theme.ts
  src/styles/typo.ts
Labels: 📦 Deploy / Release

#24 style: HeroImage, AlertText 공통 컴포넌트 제작
  src/assets/LoginImage.svg
  src/components/AlertText.tsx
  src/components/HeroImage.tsx
Labels: 🎨 Design, ⚙️ Feature

#20 feature: Button 공통 컴포넌트 제작
  src/assets/icons/KakaoIcon.tsx
  src/assets/icons/NaverIcon.tsx
  src/components/common/Buttons/IconButton/IconButtonStyles.ts
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoin.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/Buttons/NormalButton/NormalButton.tsx
  src/components/common/Buttons/NormalButton/NormalButtonStyles.ts
  src/components/common/Buttons/index.tsx
  src/components/common/Divider/index.tsx
  src/components/common/Text/index.tsx
  src/styles/palette.ts
  src/styles/typo.ts
  src/utils/getTimeStamp.ts
Labels: 🎨 Design, ⚙️ Feature

#32 [Style] flexbox 컴포넌트 제작
  src/components/common/Flexbox/index.tsx
Labels: 🎨 Design

#33 [Style] spacing 컴포넌트 생성
  src/components/common/Spacing/index.tsx
Labels: 🎨 Design

#29 [Feature] mock service worker settings
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  tsconfig.json
Labels: ⚙️ Feature

#34 style: BottomSheet 컴포넌트 제작
  package-lock.json
  package.json
  src/components/common/AlertText/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BottomSheet/ProfileSheet.tsx
  src/components/common/BottomSheet/RandomMatchingSheet.tsx
  src/components/common/BottomSheet/Timer.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoin.tsx
  src/components/common/Buttons/index.tsx
  src/components/common/HeroImage/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#37 [Style/] navigation bar 컴포넌트 제작
  src/assets/images/defaultProfileImage.png
  src/components/common/Avatar/index.tsx
  src/components/common/NavigationBar/index.tsx
Labels: 🎨 Design

#38 style: CountNumber 공통 컴포넌트 제작
  src/components/CountNumber.tsx
  src/components/Input.tsx
Labels: 🎨 Design, ⚙️ Feature

#41 style: InputTimer 공통 컴포넌트 제작
  src/components/CountNumber.tsx
  src/components/common/InputTimer/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#46 style: WhiteSelectorButton, DarkSelectorButton 공통 컴포넌트
  src/components/common/DarkSelectorButton/index.tsx
  src/components/common/WhiteSelectorButton/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#43 style: ListRow 컴포넌트 제작
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoin.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/Divider/index.tsx
  src/components/common/ListRow/AdminListRow.tsx
  src/components/common/ListRow/ProfileListRow.tsx
  src/styles/global.ts
Labels: 🎨 Design, ⚙️ Feature

#48 style: useToast 커스텀 훅 제작
  src/components/common/BottomSheet/RandomMatchingSheet.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoin.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoinButton.tsx
  src/components/common/Buttons/NormalButton/NormalButton.tsx
  src/components/layouts/Layout.tsx
  src/hooks/useToast.tsx
Labels: 🎨 Design, ⚙️ Feature

#52 [Style] Modal 컴포넌트 제작
  package-lock.json
  package.json
  src/assets/icons/Exclamation.svg
  src/assets/icons/Warning.svg
  src/components/common/Buttons/NormalButton/NormalButton.tsx
  src/components/common/Buttons/NormalButton/NormalButtonStyles.ts
  src/components/common/Modal/index.tsx
  src/components/layouts/Layout.tsx
  src/hooks/useModal.tsx
  src/store/ModalStore.tsx
  tsconfig.json
Labels: 🎨 Design, ⚙️ Feature

#55 style: selector button 공통 컴포넌트
  src/components/common/DarkSelectorButton/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/WhiteSelectorButton/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#57 style: Appbar, Card, GradationBackground, PageContainer 컴포넌트 추가 + Home 페이지 레이아웃 추가
  src/components/CountNumber.tsx
  src/components/common/AppHeader/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BottomSheet/RandomMatchingSheet.tsx
  src/components/common/Buttons/IconButton/IconButtonStyles.ts
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/Buttons/NormalButton/NormalButton.tsx
  src/components/common/Buttons/NormalButton/NormalButtonStyles.ts
  src/components/common/Buttons/NormalButton/index.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/PageContainer/index.tsx
  src/components/home/AvatarGroup.tsx
  src/components/home/Card.tsx
  src/components/home/Tip.tsx
  src/components/layouts/Layout.tsx
  src/pages/home/Home.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/index.tsx
  src/styles/global.ts
  src/styles/palette.ts
  src/styles/typo.ts
Labels: 🎨 Design, ⚙️ Feature, 🧹 Refactor

#58 deploy: 1차 스프린트 배포
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/assets/LoginImage.svg
  src/assets/icons/Exclamation.svg
  src/assets/icons/KakaoIcon.tsx
  src/assets/icons/NaverIcon.tsx
  src/assets/icons/Warning.svg
  src/assets/images/defaultProfileImage.png
  src/components/CountNumber.tsx
  src/components/Input.tsx
  src/components/common/AlertText/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BottomSheet/ProfileSheet.tsx
  src/components/common/BottomSheet/RandomMatchingSheet.tsx
  src/components/common/BottomSheet/Timer.tsx
  src/components/common/Buttons/IconButton/IconButtonStyles.ts
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoin.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoinButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/Buttons/NormalButton/NormalButton.tsx
  src/components/common/Buttons/NormalButton/NormalButtonStyles.ts
  src/components/common/CountNumber/index.tsx
  src/components/common/DarkSelectorButton/index.tsx
  src/components/common/Divider/index.tsx
  src/components/common/Flexbox/index.tsx
  src/components/common/HeroImage/index.tsx
  src/components/common/InputTimer/index.tsx
  src/components/common/ListRow/AdminListRow.tsx
  src/components/common/ListRow/ProfileListRow.tsx
  src/components/common/Loading/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/Spacing/index.tsx
  src/components/common/Text/index.tsx
  src/components/common/WhiteSelectorButton/index.tsx
  src/components/layouts/Layout.tsx
  src/hooks/useModal.tsx
  src/hooks/useToast.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/store/ModalStore.tsx
  src/styles/global.ts
  src/styles/palette.ts
  src/styles/typo.ts
  src/utils/getTimeStamp.ts
  tsconfig.json
Labels: 📦 Deploy / Release

#60 deploy: 1차 스프린트 배포 (2)
  src/assets/icons/ExitIcon.tsx
  src/components/common/AppHeader/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BackChevron/index.tsx
  src/components/common/BottomSheet/RandomMatchingSheet.tsx
  src/components/common/Buttons/IconButton/IconButtonStyles.ts
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/Buttons/NormalButton/NormalButtonStyles.ts
  src/components/common/Buttons/NormalButton/index.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/PageContainer/index.tsx
  src/components/common/PageHeader/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/home/AvatarGroup.tsx
  src/components/home/Card.tsx
  src/components/home/Tip.tsx
  src/components/layouts/Layout.tsx
  src/main.tsx
  src/pages/home/Home.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/index.tsx
  src/styles/global.ts
  src/styles/palette.ts
  src/styles/typo.ts
Labels: 📦 Deploy / Release
