Repository coffee-meet/frontend, pull requests merged in 2023-12, with the labels that each got.

#203 deploy: 배포 테스트
  src/apis/adminReport/AdminReportApi.ts
  src/components/common/AppHeader/AdminAppHeader.tsx
  src/components/common/ListRow/AdminApprovalList.tsx
  src/components/common/ListRow/AdminApprovalListRowTitle.tsx
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminReportList.tsx
  src/components/home/Card.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminInquiryInfo.tsx
  src/pages/admin/components/AdminPageHeader.tsx
  src/pages/admin/components/AdminTabs.tsx
Labels: 📦 Deploy / Release

#205 feature: AdminAPI6
  src/apis/adminApproval/AdminApprovalApi.ts
  src/components/common/ListRow/AdminReportList.tsx
Labels: ⚙️ Feature

#208 featuer: API7
  src/apis/adminApproval/AdminApprovalApi.ts
  src/pages/admin/components/AdminApprovalInfo.tsx
Labels: ⚙️ Feature

#209 deploy: 배포테스트 (5)
  src/apis/adminApproval/AdminApprovalApi.ts
  src/pages/admin/components/AdminApprovalInfo.tsx
Labels: 📦 Deploy / Release

#213 배포 테스트
  src/pages/chatting/Chatting.tsx
Labels: 📦 Deploy / Release

#215 feature: AdminAPI (9)
  src/apis/adminApproval/AdminApprovalApi.ts
  src/components/common/ListRow/AdminApprovalList.tsx
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminReportList.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminTabs.tsx
Labels: ⚙️ Feature

#220 [Feature]: 마이페이지 영역 페이지 3종 추가
  src/apis/profile/getMyProfileData.ts
  src/apis/profile/postMyInquiry.ts
  src/apis/profile/postMyProfileImage.ts
  src/apis/profile/type.ts
  src/apis/profile/updateMyProfile.ts
  src/apis/register/getEmailValid.ts
  src/apis/register/getNicknameValid.ts
  src/apis/register/registerCompanyInfo.ts
  src/apis/register/sendEmailValidCode.ts
  src/components/common/PageHeader/index.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/profile/ProfileHelpDesk.tsx
  src/pages/profile/ProfilePrivacy.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
Labels: ⚙️ Feature

#224 배포 테스트
  src/pages/chatting/Chatting.tsx
Labels: 📦 Deploy / Release

#225 배포 테스트
  src/pages/chatting/Chatting.tsx
Labels: 📦 Deploy / Release

#227 배포 테스트
  src/components/home/Card.tsx
  src/pages/chatting/Chatting.tsx
Labels: 📦 Deploy / Release

#228 배포 테스트
  src/components/home/Card.tsx
Labels: 📦 Deploy / Release

#229 배포 테스트
  src/components/home/Card.tsx
Labels: 📦 Deploy / Release

#236 배포 테스트
  src/pages/home/Home.tsx
  src/pages/profile/ProfileEdit.tsx
Labels: 📦 Deploy / Release

#237 배포 테스트
  src/pages/profile/ProfileEdit.tsx
Labels: 📦 Deploy / Release

#248 Refactor: 구 관심사 & 직무 정보 선택 UI 리팩터링
  src/components/common/CustomSelectorButton/index.tsx
  src/components/common/DarkSelectorButton/index.tsx
  src/components/common/MultiSelector/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/constants/index.ts
  src/pages/profile/ProfileEdit.tsx
  src/pages/profile/ProfilePrivacy.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
Labels: 🧹 Refactor

#252 재배포 테스트
  .github/workflows/deploy.yml
Labels: 📦 Deploy / Release

#254 Refactor: 회사 정보 등록 및 수정 페이지 폼 개선
  package-lock.json
  package.json
  src/components/common/CountNumber/index.tsx
  src/components/common/RegisterInput/index.tsx
  src/pages/chatList/ChatList.tsx
  src/pages/chatListDetail/ChatListDetail.tsx
  src/pages/chatting/Chatting.tsx
  src/pages/chatting/components/chatBubbleListLow/index.tsx
  src/pages/chatting/components/chatList/ChatRoomBubble.tsx
  src/pages/chatting/components/chatList/ChatRoomBubbles.tsx
  src/pages/chatting/components/dateTime/index.tsx
  src/pages/chatting/components/messageArea/index.tsx
  src/pages/home/Home.tsx
  src/pages/home/components/AvatarGroup.tsx
  src/pages/home/components/Card.tsx
  src/pages/home/components/CardBottom.tsx
  src/pages/home/components/CardHeader.tsx
  src/pages/home/components/CardMiddle.tsx
  src/pages/home/components/Tip.tsx
  src/pages/profile/ProfileCompanyEdit.tsx
  src/pages/profile/ProfilePrivacy.tsx
  src/pages/profile/index.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/schemas/companyInfo.ts
  src/store/JobStore.tsx
  tsconfig.json
Labels: 🧹 Refactor
