Repository coffee-meet/frontend, pull requests merged in 2023-11, with the labels that each got.

#65 [Style] chatting bubble 컴포넌트 제작 및 소켓 라이브러리 설치
  package-lock.json
  package.json
  setupProxy.ts
  src/components/common/ChattingText/index.tsx
  src/components/common/chattingBubble/index.tsx
  tsconfig.json
  vite.config.ts
Labels: 🎨 Design

#62 style: BusinessCardContainer 공통 컴포넌트 (재PR)
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/Text/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#76 test: API Test 코드
  src/apis/test.ts
  src/components/common/AlertText/index.tsx
  src/components/common/CountNumber/index.tsx
  src/components/common/CustomSelectorButton/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/pages/profile/ProfileEdit.tsx
Labels: ⚙️ Feature

#77 deploy: 백엔드 API Test를 위한 배포
  package-lock.json
  package.json
  setupProxy.ts
  src/apis/test.ts
  src/components/common/AlertText/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/ChattingText/index.tsx
  src/components/common/CountNumber/index.tsx
  src/components/common/CustomSelectorButton/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/components/common/Text/index.tsx
  src/components/common/chattingBubble/index.tsx
  src/pages/profile/ProfileEdit.tsx
  src/styles/global.ts
  tsconfig.json
  vite.config.ts
Labels: 📦 Deploy / Release

#78 test: retest
  src/apis/test.ts
Labels: ⚙️ Feature

#79 deploy: API Test를 위한 배포
  package-lock.json
  src/apis/test.ts
  src/components/common/Buttons/IconButton/index.tsx
  src/styles/global.ts
Labels: 📦 Deploy / Release

#80 fix: vite 설정 (cors)
  vite.config.ts
Labels: 🔨 Fix, ⚙️ Feature

#81 deploy: Vite CORS 설정 추가 배포
  package-lock.json
  src/components/common/Buttons/IconButton/index.tsx
  vite.config.ts
Labels: 📦 Deploy / Release

#82 fix: cors 재설정
  src/apis/test.ts
Labels: 🔨 Fix

#83 deploy: 백엔드 API 통신 테스트 배포
  src/apis/test.ts
Labels: 📦 Deploy / Release

#84 fix: vite 설정 변경
  src/apis/test.ts
  vite.config.ts
Labels: 🔨 Fix

#85 deploy: vite 설정 수정
  src/apis/test.ts
  src/components/common/SelectorButton/index.tsx
  vite.config.ts
Labels: 📦 Deploy / Release

#86 fix: axios 파일 수정
  src/apis/test.ts
  src/pages/profile/ProfileDefault.tsx
Labels: 🔨 Fix

#88 deploy: axios 파일 수정
  src/apis/test.ts
  src/pages/profile/ProfileDefault.tsx
Labels: 📦 Deploy / Release

#92 fix: REST API 주소 코드 수정
  src/apis/test.ts
Labels: 🔨 Fix

#93 deploy: 백엔드 REST API 통신 테스트
  src/apis/test.ts
Labels: 📦 Deploy / Release

#68 refactor: AlertText, CountNumber 공통 컴포넌트 수정
  src/components/common/BusinessCardContainer/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#94 feature: HomePage 다크모드 기능 추가 + Card 컴포넌트 분리 + timerWorker 추가
  public/timerWorker.js
  src/components/common/AppHeader/index.tsx
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoinButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/PageContainer/index.tsx
  src/components/home/Card.tsx
  src/components/home/CardBottom.tsx
  src/components/home/CardHeader.tsx
  src/components/home/CardMiddle.tsx
  src/components/home/Tip.tsx
  src/pages/home/Home.tsx
  src/store/ThemeStore.tsx
  src/store/TimerStore.tsx
  src/styles/palette.ts
Labels: ⚙️ Feature, 🧹 Refactor

#96 style: LoginPage 레이아웃 작성
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/HeroImage/index.tsx
  src/pages/login/Login.tsx
Labels: 🎨 Design

#102 feature: NotFoundPage 제작
  src/assets/icons/NotFoundIcon.tsx
  src/components/common/GradationBackground/index.tsx
  src/pages/notFound/NotFound.tsx
  src/styles/typo.ts
Labels: 🎨 Design, ⚙️ Feature

#70 refactor: SelectorButton 공통 컴포넌트 수정
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#71 style: CustomSelectorButton 공통 컴포넌트
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/CustomSelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#72 style: SelectorButtonContainer 공통 컴포넌트
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
Labels: 🎨 Design, ⚙️ Feature

#90 refactor: Input 컴포넌트 ref, onchange 추가
  src/components/common/Input/index.tsx
Labels: 🧹 Refactor

#107 feature: 로그인 페이지 OAuth 연결 + 반응형 레이아웃 구성
  src/App.tsx
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/HeroImage/index.tsx
  src/components/common/Spacing/index.tsx
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/loginPending/index.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
Labels: ⚙️ Feature

#112 deploy: 3차 스프린트 배포
  public/timerWorker.js
  src/App.tsx
  src/assets/icons/NotFoundIcon.tsx
  src/components/common/AppHeader/index.tsx
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingJoinButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/CustomSelectorButton/index.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/HeroImage/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/PageContainer/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/components/common/Spacing/index.tsx
  src/components/home/Card.tsx
  src/components/home/CardBottom.tsx
  src/components/home/CardHeader.tsx
  src/components/home/CardMiddle.tsx
  src/components/home/Tip.tsx
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/loginPending/index.tsx
  src/pages/notFound/NotFound.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
  src/store/ThemeStore.tsx
  src/store/TimerStore.tsx
  src/styles/palette.ts
  src/styles/typo.ts
Labels: 📦 Deploy / Release

#113 hotfix: VITE_BASE_URL 환경변수 설정
  .env.production
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/GradationBackground/index.tsx
Labels: 🔨 Fix

#114 deploy: VITE_BASE_URL 배포 테스트
  .env.production
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/Input/index.tsx
Labels: 🔨 Fix, 📦 Deploy / Release

#115 hotfix: 로그인 API 수정 재배포
  src/components/common/GradationBackground/index.tsx
  src/pages/loginPending/LoginPending.tsx
Labels: 🔨 Fix, 📦 Deploy / Release

#119 [Feature] 사용자의 닉네임, 관심사 정보 등록 페이지 구현
  package-lock.json
  package.json
  src/apis/axios.ts
  src/components/common/PageHeader/index.tsx
  src/components/common/RegisterInput/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/pages/register/RegisterUser.tsx
  src/store/InterestStore.tsx
Labels: 🎨 Design, ⚙️ Feature

#121 [Fix] 관심사 버튼 해제 시 전역 store에 반영되지 않는 문제 해결
  package-lock.json
  package.json
  src/apis/axios.ts
  src/components/common/SelectorButton/index.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/pages/register/RegisterUser.tsx
Labels: 🔨 Fix

#109 feature: 프로필 페이지 제작
  public/mockServiceWorker.js
  src/assets/icons/KakaoIcon.tsx
  src/assets/icons/NaverIcon.tsx
  src/components/common/AppHeader/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BackChevron/index.tsx
  src/components/common/Buttons/IconButton/IconButtonStyles.ts
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/Divider/index.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/ListRow/ProfileListRow.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/PageHeader/index.tsx
  src/components/common/Text/index.tsx
  src/components/home/Card.tsx
  src/hooks/useModal.tsx
  src/mocks/handlers.ts
  src/pages/chatList/ChatList.tsx
  src/pages/home/Home.tsx
  src/pages/notFound/NotFound.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/store/ModalStore.tsx
Labels: 🎨 Design, ⚙️ Feature

#125 [Feature] 실시간 채팅 기능 및 상대방 프로필 클릭 시 상대방 프로필 조회 기능
  setupProxy.ts
  src/apis/axios.ts
  src/apis/chatting/chattingApi.ts
  src/apis/chatting/chattingType.ts
  src/assets/icons/Send.svg
  src/components/chatBubbleListLow/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BottomSheet/ProfileSheet.tsx
  src/components/common/ChattingText/index.tsx
  src/components/common/TextArea/index.tsx
  src/components/common/chattingBubble/index.tsx
  src/components/dateTime/index.tsx
  src/components/messageArea/index.tsx
  src/mocks/handlers.ts
  src/pages/chatting/Chatting.tsx
  src/store/BottomSheetStore.tsx
Labels: 🎨 Design, ⚙️ Feature

#127 [Fix] 카카오 로그인 성공 시 토큰 불러오는 함수 무한루프 제거
  src/mocks/handlers.ts
  src/pages/loginPending/LoginPending.tsx
Labels: 🔨 Fix

#128 배포 테스트
  public/mockServiceWorker.js
  setupProxy.ts
  src/apis/axios.ts
  src/apis/chatting/chattingApi.ts
  src/apis/chatting/chattingType.ts
  src/assets/icons/KakaoIcon.tsx
  src/assets/icons/NaverIcon.tsx
  src/assets/icons/Send.svg
  src/components/chatBubbleListLow/index.tsx
  src/components/common/AppHeader/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/BackChevron/index.tsx
  src/components/common/BottomSheet/ProfileSheet.tsx
  src/components/common/Buttons/IconButton/IconButtonStyles.ts
  src/components/common/Buttons/IconButton/InterestButton.tsx
  src/components/common/Buttons/IconButton/index.tsx
  src/components/common/ChattingText/index.tsx
  src/components/common/Divider/index.tsx
  src/components/common/GradationBackground/index.tsx
  src/components/common/ListRow/ProfileListRow.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/PageHeader/index.tsx
  src/components/common/Text/index.tsx
  src/components/common/TextArea/index.tsx
  src/components/common/chattingBubble/index.tsx
  src/components/dateTime/index.tsx
  src/components/messageArea/index.tsx
  src/hooks/useModal.tsx
  src/mocks/handlers.ts
  src/pages/chatList/ChatList.tsx
  src/pages/chatting/Chatting.tsx
  src/pages/home/Home.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/notFound/NotFound.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/store/BottomSheetStore.tsx
  src/store/ModalStore.tsx
Labels: 📦 Deploy / Release

#130 로그인 배포 테스트
  src/components/common/Avatar/index.tsx
  src/components/common/PageHeader/index.tsx
  src/pages/chatList/ChatList.tsx
  src/pages/loginPending/LoginPending.tsx
Labels: 📦 Deploy / Release

#132 [Feature] 회사 정보 등록 페이지 구현
  src/apis/axios.ts
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
Labels: ⚙️ Feature

#135 [Fix] provider 대문자로 수정 및 회사 등록 페이지 form 별로 예외 처리
  src/apis/axios.ts
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/register/RegisterCompany.tsx
  src/store/AuthStore.tsx
Labels: 🔨 Fix

#137 [Deploy] 로그인 회원가입 배포 테스트
  src/apis/axios.ts
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/register/RegisterCompany.tsx
  src/store/AuthStore.tsx
Labels: 📦 Deploy / Release

#140 fix: login 페이지 스크롤 속성 추가
  src/apis/adminApproval/AdminApprovalApi.ts
  src/apis/adminLogin/AdminLoginApi.ts
  src/apis/adminReport/AdminReportApi.ts
  src/components/common/ListRow/AdminApprovalList.tsx
  src/mocks/handlers.ts
  src/mocks/handlersInterface.ts
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminReportInfo.tsx
  src/pages/admin/index.tsx
  src/pages/login/Login.tsx
Labels: 🔨 Fix

#141 🐛 [Bug]: OAuth 인증 코드 분리 로직 추가
  src/apis/axios.ts
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
Labels: 🔨 Fix

#142 [Deploy] 로그인 로직 수정 배포 테스트
  src/apis/adminApproval/AdminApprovalApi.ts
  src/apis/adminLogin/AdminLoginApi.ts
  src/apis/adminReport/AdminReportApi.ts
  src/apis/axios.ts
  src/components/common/ListRow/AdminApprovalList.tsx
  src/mocks/handlers.ts
  src/mocks/handlersInterface.ts
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminReportInfo.tsx
  src/pages/admin/index.tsx
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
Labels: 📦 Deploy / Release

#131 feature: 관리자 페이지 로그인 (현재까지 진행 사항 PR)
  src/App.tsx
  src/apis/adminApproval/AdminApprovalApi.ts
  src/apis/adminReport/AdminReportApi.ts
  src/assets/images/inquiry.svg
  src/components/common/AppHeader/index.tsx
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/ListRow/AdminInquiryListRow.tsx
  src/mocks/handlers.ts
  src/mocks/handlersInterface.ts
  src/pages/admin/AdminInquiry.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminInquiryBtn.tsx
  src/pages/admin/components/AdminReportInfo.tsx
  src/pages/admin/components/AdminTabs.tsx
Labels: ⚙️ Feature

#152 Fix: 관리자 페이지 API 요청 주소 수정
  src/apis/adminApproval/AdminApprovalApi.ts
  src/apis/adminLogin/AdminLoginApi.ts
  src/apis/adminReport/AdminReportApi.ts
Labels: 🔨 Fix

#153 feature: 관리자 페이지 - 문의 리스트 컴포넌트 추가, 문의 상세 페이지 추가
  src/apis/adminApproval/AdminApprovalApi.ts
  src/apis/adminInquiry/AdminInquiryApi.ts
  src/assets/images/inquiry.svg
  src/assets/images/inquiryImage.svg
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminInquiryListRow.tsx
  src/mocks/handlers.ts
  src/mocks/handlersInterface.ts
  src/pages/admin/AdminInquiry.tsx
  src/pages/admin/components/AdminInquiryInfo.tsx
Labels: 🎨 Design

#154 [Feature]: BE OAuth 인증 로직 변경에 따른 적용
  src/components/common/AppHeader/index.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/pages/admin/components/AdminInquiryBtn.tsx
  src/pages/home/Home.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
  src/store/JobStore.tsx
Labels: 🔨 Fix, ⚙️ Feature

#156 [Deploy]: 현재까지 작업 배포
  src/App.tsx
  src/apis/adminApproval/AdminApprovalApi.ts
  src/apis/adminInquiry/AdminInquiryApi.ts
  src/apis/adminLogin/AdminLoginApi.ts
  src/apis/adminReport/AdminReportApi.ts
  src/assets/images/inquiryImage.svg
  src/components/common/AppHeader/index.tsx
  src/components/common/BusinessCardContainer/index.tsx
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminInquiryListRow.tsx
  src/components/common/SelectorButton/index.tsx
  src/components/common/SelectorButtonContainer/index.tsx
  src/mocks/handlers.ts
  src/mocks/handlersInterface.ts
  src/pages/admin/AdminInquiry.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminInquiryBtn.tsx
  src/pages/admin/components/AdminInquiryInfo.tsx
  src/pages/admin/components/AdminReportInfo.tsx
  src/pages/admin/components/AdminTabs.tsx
  src/pages/home/Home.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
  src/store/JobStore.tsx
Labels: 📦 Deploy / Release

#148 [Feature] fcm 서비스 워커 세팅 및 랜덤 매칭 성공 시 web push 기능 구현
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  setupProxy.ts
  src/App.tsx
  src/apis/axios.ts
  src/components/common/Buttons/IconButton/ParticularTopicButton.tsx
  src/components/common/Buttons/IconButton/RandomMatchingButton.tsx
  src/components/common/Buttons/NormalButton/NormalButtonStyles.ts
  src/components/home/Card.tsx
  src/components/home/Tip.tsx
  src/firebase-messaging-sw.ts
  src/pages/chatting/Chatting.tsx
  src/pages/home/Home.tsx
  tsconfig.json
Labels: ⚙️ Feature

#162 [Feat] 마이 프로필 페이지 조회 기능
  src/pages/profile/ProfileDefault.tsx
Labels: ⚙️ Feature

#167 배포 테스트
  src/firebase-messaging-sw.ts
  src/pages/chatList/ChatList.tsx
Labels: 📦 Deploy / Release

#171 [Deploy] 채팅 히스토리, 마이페이지 수정 후 배포 테스트
  src/components/chatList/ChatRoomBubbles.tsx
  src/pages/chatList/ChatList.tsx
  src/pages/profile/ProfileDefault.tsx
Labels: 📦 Deploy / Release

#175 feature: 관리자페이지 API 요청 (1)
  src/apis/adminLogin/AdminLoginApi.ts
  src/components/common/Buttons/IconButton/KakaoButton.tsx
  src/components/common/Buttons/IconButton/NaverButton.tsx
  src/components/common/HeroImage/index.tsx
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminReportList.tsx
  src/components/common/ListRow/AdminReportListRow.tsx
  src/components/common/ListRow/AdminReportersList.tsx
  src/mocks/handlers.ts
  src/mocks/handlersInterface.ts
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/components/AdminApprovalInfo.tsx
  src/pages/admin/components/AdminInquiryInfo.tsx
  src/pages/admin/components/AdminReportInfo.tsx
  src/pages/admin/components/AdminTabs.tsx
  src/pages/login/Login.tsx
Labels: ⚙️ Feature

#181 [Fix] 유저의 매칭 상태에 따라 화면 반영
  src/components/home/Card.tsx
Labels: 🔨 Fix

#183 [Deploy] 배포 테스트
  src/components/common/Avatar/index.tsx
  src/components/home/Card.tsx
Labels: 🔨 Fix

#185 feature: 관리자페이지(배포 환경) mock data 추가
  src/components/common/ListRow/AdminApprovalList.tsx
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminReportList.tsx
  src/components/common/ListRow/AdminReportersList.tsx
Labels: ⚙️ Feature

#186 [Deploy] 배포 테스트
  src/components/messageArea/index.tsx
  src/pages/chatting/Chatting.tsx
Labels: 📦 Deploy / Release

#197 배포 테스트
  src/pages/chatting/Chatting.tsx
Labels: 📦 Deploy / Release

#198 feature: 문의 리스트, 신고 리스트 전체 조회 API 요청
  src/components/common/ListRow/AdminInquiryList.tsx
  src/components/common/ListRow/AdminReportList.tsx
  src/components/common/ListRow/AdminReportListRow.tsx
  src/components/common/chattingBubble/index.tsx
Labels: ⚙️ Feature
