Repository coffee-meet/frontend, pull requests merged in 2024-01, with the labels that each got.

#255 [Refactor] 회원정보 등록, 프로필 편집 페이지 react-hook-form, zod로 폼 관리하도록 변경
  src/pages/profile/ProfileEdit.tsx
  src/pages/register/RegisterUser.tsx
  src/schemas/userInfo.ts
Labels: 🧹 Refactor

#258 Fix: 회원 정보 등록 시점 변경
  src/apis/register/registerUserInfo.ts
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
Labels: 🔨 Fix

#259 Deploy: 현재까지 작업 배포
  src/apis/register/registerUserInfo.ts
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
Labels: 📦 Deploy / Release

#267 Fix: 로그아웃 시 API 요청 로직 추가
  src/pages/profile/ProfileDefault.tsx
Labels: 🔨 Fix, 📦 Deploy / Release

#274 Bug: 닉네임 5글자 넘어가면 레이아웃 깨지는 현상 외 1건 수정
  src/apis/profile/type.ts
  src/components/common/AppHeader/index.tsx
  src/pages/home/Home.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/register/RegisterUser.tsx
  src/schemas/userInfo.ts
Labels: 🎨 Design, 🧹 Refactor

#275 Deploy: 현재까지 작업 배포
  src/apis/profile/type.ts
  src/components/common/AppHeader/index.tsx
  src/pages/home/Home.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/register/RegisterUser.tsx
  src/schemas/userInfo.ts
Labels: 📦 Deploy / Release

#277 Fix: 인증 관련 정보 정리 외 자잘한 수정
  src/apis/axios.ts
  src/apis/profile/getMyProfileData.ts
  src/apis/queryClient.ts
  src/components/common/AppHeader/index.tsx
  src/components/common/MultiSelector/index.tsx
  src/libs/react-query/options/getMyProfileData.ts
  src/pages/chatting/Chatting.tsx
  src/pages/chatting/components/messageArea/index.tsx
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/profile/ProfileCompanyEdit.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
  tsconfig.json
Labels: 🔨 Fix, ⚙️ Feature, 🧹 Refactor

#278 Deploy: 지금까지 작업 배포
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/apis/axios.ts
  src/apis/profile/getMyProfileData.ts
  src/apis/queryClient.ts
  src/components/common/AppHeader/index.tsx
  src/components/common/MultiSelector/index.tsx
  src/libs/react-query/options/getMyProfileData.ts
  src/pages/chatting/Chatting.tsx
  src/pages/chatting/components/messageArea/index.tsx
  src/pages/login/Login.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/profile/ProfileCompanyEdit.tsx
  src/pages/profile/ProfileDefault.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/store/AuthStore.tsx
  tsconfig.json
Labels: 📦 Deploy / Release

#281 Fix: 소소한 수정 권장되는 부분들 수정
  src/apis/test.ts
  src/components/common/MultiSelector/index.tsx
  src/components/common/NavigationBar/index.tsx
  src/components/common/RegisterInput/index.tsx
  src/components/common/WhiteSelectorButton/index.tsx
  src/pages/chatListDetail/ChatListDetail.tsx
  src/pages/loginPending/LoginPending.tsx
  src/pages/profile/ProfileCompanyEdit.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/register/RegisterCompany.tsx
  src/pages/register/RegisterUser.tsx
  src/styles/palette.ts
Labels: 🔨 Fix, 🎨 Design
